### ISSUE TITLE
useMap에서 remove() 타입 에러 해결

### ISSUE THREAD

**Issue by smosco** [Seoul-Public-Data/seoul_frontend#39]

**Comment by stu442** [comment]
타입 에러 관련해서 제가 Tmap 공식 문서를 보다가 발견한건데요!!

remove라는 메서드는 없는 것 같습니다.
destroy라는 메서드는 있는데 이걸 사용해보는건 어떨까요??

추가적으로 저는 useMap에 useEffect에 map이 있는지 확인하는 로직도 넣었더니 오류가 더이상 없었습니다!!
곧 관련해서 PR 날리겠습니다.

<img width="969" alt="image" src="https://github.com/Seoul-Public-Data/seoul_frontend/assets/104495388/6b0bd358-2a93-4d0b-a085-a0245ec24aac">
